[package]
name = "rbuilder-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
parking_lot.workspace = true
revm.workspace = true
reth-evm.workspace = true
reth-errors.workspace = true
ahash.workspace = true
alloy-primitives.workspace = true
derive_more.workspace = true
lru.workspace = true
tracing.workspace = true
dashmap.workspace = true
itertools.workspace = true
revm-inspectors.workspace = true
alloy-consensus.workspace = true
reth-primitives.workspace = true
reth.workspace = true
thiserror.workspace = true